baseURL = "https://delphi.cmu.edu/covidcast"
languageCode = "en-us"
title = "COVIDcast"
theme = "delphi"
googleAnalytics = "UA-88748454-1"
disqusShortname = ""
relativeURLs = true
ignoreFiles = ["src", "node_modules", ".github", "cypress", "scripts", "static/bundle", "package.json"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Delphi"
    url = "https://delphi.cmu.edu/"
    weight = 1
[[menu.main]]
    identifier = "main"
    name = "COVIDcast"
    url = "/"
    weight = 2
[[menu.main]]
    name = "Data"
    url = "https://cmu-delphi.github.io/delphi-epidata/"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "https://delphi.cmu.edu/blog"
    weight = 4
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/cmu-delphi/"
    weight = 5

[params]
    description = "Developing the Theory and Practice of Epidemiological Forecasting"
    showReadMore = true

    [params.logo]
    url = "delphi_logo.png"
    width = 50
    height = 50
    alt = "Logo"
